DATA_DIR=/work/donglab/ching.ki/ssRNA-MD/MD_sim/data
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m11.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m12.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m13.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m14.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m15.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m16.pdb 50 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 10 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 20 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 30 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 40 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 50 Na+
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 10 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 20 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 30 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 40 MG
#sbatch pipeline.sh $DATA_DIR/sasdfb9_m17.pdb 50 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 10 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 20 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 30 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 40 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 50 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 10 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 20 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 30 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 40 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m18.pdb 50 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 10 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 20 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 30 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 40 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 50 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 10 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 20 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 30 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 40 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m19.pdb 50 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 10 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 20 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 30 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 40 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 50 Na+
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 10 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 20 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 30 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 40 MG
sbatch pipeline.sh $DATA_DIR/sasdfb9_m20.pdb 50 MG
